#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sudo cpupower frequency-set --governor conservative &

sudo bash ~/scripts/wakeup.sh &

feh --bg-fill ~/scripts/wallpapers/world.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config focused_border_color \#8ec07c
bspc config normal_border_color  \#ebdbb2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config top_padding         62

bspc rule -a Zathura state=tiled 
