#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/scripts/lemonbar.sh | lemonbar -g 2536x43+12+12 -f 'TerminessTTF Nerd Font:size=20' -B '#ffffff' &

sudo cpupower frequency-set --governor conservative &

sudo bash ~/scripts/wakeup.sh &

feh --bg-fill ~/scripts/wallpapers/flower.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12

bspc config focused_border_color \#8ec07c
bspc config normal_border_color  \#ebdbb2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config top_padding         55

bspc rule -a Zathura state=tiled 

bspc rule -d '^9' state=monocle

