#!/bin/sh

# Variable setting
#export PATH=/usr/local/texlive/2022/bin/x86_64-linux:$PATH
export PATH=/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR='nvim'
export ZSH=$HOME/.config/myzsh

ZSH_COMPDUMP="$HOME/.config/myzsh/zcompdump-${ZSH_VERSION}"
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Load all stock functions (from $fpath files) called below.
autoload -U compaudit compinit
compinit -u -C -d "${ZSH_COMPDUMP}"

# Add all defined plugins to fpath. This must be done before running compinit.
for plugin ($plugins); do
	fpath=($ZSH/plugins/$plugin $fpath)
done

# Load all of the plugins
plugins=(git sudo colorize fzf zsh-completions zsh-autosuggestions zsh-syntax-highlighting zsh-autopair fzf-tab-completion)

for plugin ($plugins); do
	if [ -f $ZSH/plugins/$plugin/$plugin.plugin.zsh ]; then
		source $ZSH/plugins/$plugin/$plugin.plugin.zsh
	fi
done

# Load theme
source "$ZSH/themes/git.zsh"
source "$ZSH/themes/ren.zsh-theme"

# Config fzf-tab-completion
export FZF_COMPLETION_TRIGGER='f'
export FZF_TMUX=1
export FZF_TMUX_HEIGHT='100%'

# Alias
alias px='proxychains4'
alias ne='clear && echo "\n" && neofetch --ascii_distro Linux'
alias xm="xmodmap ~/.config/Xmodmap"
alias xn="xmodmap ~/.config/xmodmap"
alias bl="bluetoothctl"
alias is="sudo iw dev wlan0 scan | grep SSID"
alias io="sudo iw dev wlan0 connect CNU"
alias ik="sudo iw dev wlan0 disconnect"
alias ih="iw dev wlan0 info"
alias se="./scripts/se.sh"
alias sd="startx"
alias em="emacs -nw"
alias ra="ranger"
alias vv="v2ray -c ~/scripts/config.json"
alias psy="sudo pacman -Syyu"
alias ps="sudo pacman -S"
alias pr="sudo pacman -Rns"
alias pq="sudo pacman -Q"
alias pp="bash ~/scripts/passmenu2.sh"
alias cs="curl --socks5 127.0.0.1:1080"
alias vim="nvim"
alias mu="proxychains4 neomutt"
alias ke="sudo loadkeys i386/qwerty/emacs2.map.gz"
alias nx='bash ~/scripts/nextcloud.sh'
alias lg='lazygit'
alias cl='rm -rf ~/.cache ~/.local/share/qutebrowser/webengine/Local\ Storage ~/.local/share/qutebrowser/webengine/Service\ Worker ~/.local/share/qutebrowser/webengine/GPUCache ~/.dbus'

# Colorized man
man() {
	LESS_TERMCAP_md=$'\e[01;31m' \
		LESS_TERMCAP_me=$'\e[0m' \
		LESS_TERMCAP_se=$'\e[0m' \
		LESS_TERMCAP_so=$'\e[01;44;33m' \
		LESS_TERMCAP_ue=$'\e[0m' \
		LESS_TERMCAP_us=$'\e[01;32m' \
		command man "$@"
	}

# Keybinding
bindkey '^F' vi-forward-char
bindkey '' vi-backward-char
bindkey '^P' up-line-or-history
bindkey '^N' down-line-or-history

#bindkey -v

